### ISSUE TITLE
Blur on Linux (Ubuntu 24.04)

### ISSUE THREAD

**Issue by Zencaaw** [jenslys/zed-catppuccin-blur#3]
Hi, 
I put this theme on Zed on Ubuntu, and I realized it isn't the same as the pictures on MacOS.
![Screenshot from 2024-10-10 16-08-08](https://github.com/user-attachments/assets/bf3d894d-1b44-48de-8c19-f0821dcb07fb)
We saw the calculator app behind the window's Zed, it isn't blurry, but it's transparent.
Can you fix this because I love this theme and i would like to use it ?

**Comment by jenslys** [comment]
This is Zed/OS issue, not theme issue
