### ISSUE TITLE
Transparent instead of blur.

### ISSUE THREAD

**Issue by MistyDragon7** [jenslys/zed-catppuccin-blur#5]
Hello, 
I installed Zed on my new Kubuntu build, and I cannot help but notice that your theme isn't blurry - it's entirely transparent. Now while that may look nice for a bit, it quickly got annoying. Could you look into this? 
![image](https://github.com/user-attachments/assets/e7ea7733-0080-45b6-b76a-64f03d7f42d4)
Thanks!

**Comment by jenslys** [comment]
This might be an issue related to Zed itself

**Comment by danielgafni** [comment]
This probably depends on your compositor features and settings. I don't think it's a problem with Zed or the theme.
